import React, { createContext, useState, useEffect, useContext, useRef } from 'react';
import { AuthContext } from './AuthContext.jsx';
import { SocketContext } from './SocketContext.jsx';
import api from '../utils/api.js';

export const CallContext = createContext();

const rtcConfig = {
  iceServers: [
    { urls: 'stun:stun.l.google.com:19302' },
    { urls: 'stun:stun1.l.google.com:19302' },
    { urls: 'stun:stun2.l.google.com:19302' },
  ],
};

export const CallProvider = ({ children }) => {
  const { user } = useContext(AuthContext);
  const { socket } = useContext(SocketContext);

  const [callState, setCallState] = useState('idle'); // 'idle' | 'calling' (outgoing) | 'incoming' | 'connected'
  const [callType, setCallType] = useState('audio'); // 'audio' | 'video'
  const [partner, setPartner] = useState(null); // The other caller's user object
  const [localStream, setLocalStream] = useState(null);
  const [remoteStream, setRemoteStream] = useState(null);
  const [isMuted, setIsMuted] = useState(false);
  const [isCameraOff, setIsCameraOff] = useState(false);
  const [isScreenSharing, setIsScreenSharing] = useState(false);

  const peerConnectionRef = useRef(null);
  const localStreamRef = useRef(null);
  const pendingCandidates = useRef([]);
  const partnerIdRef = useRef(null);
  const incomingSignalRef = useRef(null);
  const screenStreamRef = useRef(null);

  useEffect(() => {
    if (!socket) return;

    // Listen for incoming call
    socket.on('call_incoming', async ({ signal, from, callerName, type }) => {
      try {
        const { data } = await api.get(`/users/search?q=${callerName}`);
        const callerProfile = data.find(u => u._id === from) || { _id: from, fullName: callerName, username: callerName };
        
        partnerIdRef.current = from;
        incomingSignalRef.current = signal;
        
        setPartner(callerProfile);
        setCallType(type);
        setCallState('incoming');
      } catch (error) {
        console.error('Error handling incoming call metadata:', error);
      }
    });

    // Listen for call accepted
    socket.on('call_accepted', async (signal) => {
      console.log('Call accepted by receiver. Connecting...');
      const pc = peerConnectionRef.current;
      if (pc) {
        try {
          await pc.setRemoteDescription(new RTCSessionDescription(signal));
          setCallState('connected');
          
          // Process any candidate packets that arrived early
          while (pendingCandidates.current.length > 0) {
            const cand = pendingCandidates.current.shift();
            await pc.addIceCandidate(new RTCIceCandidate(cand));
          }
        } catch (error) {
          console.error('Error establishing remote description:', error);
        }
      }
    });

    // Listen for ICE candidates
    socket.on('ice_candidate', async (candidate) => {
      const pc = peerConnectionRef.current;
      if (pc && pc.remoteDescription) {
        try {
          await pc.addIceCandidate(new RTCIceCandidate(candidate));
        } catch (error) {
          console.error('Error adding ICE candidate:', error);
        }
      } else {
        pendingCandidates.current.push(candidate);
      }
    });

    // Listen for call rejection
    socket.on('call_rejected', () => {
      console.log('Call was rejected by the recipient');
      cleanupCall();
    });

    // Listen for call ending
    socket.on('call_ended', () => {
      console.log('Call was hung up by the other user');
      cleanupCall();
    });

    return () => {
      socket.off('call_incoming');
      socket.off('call_accepted');
      socket.off('ice_candidate');
      socket.off('call_rejected');
      socket.off('call_ended');
    };
  }, [socket]);

  // Create local user media stream
  const getMediaStream = async (type) => {
    try {
      const stream = await navigator.mediaDevices.getUserMedia({
        video: type === 'video',
        audio: true,
      });
      localStreamRef.current = stream;
      setLocalStream(stream);
      return stream;
    } catch (err) {
      console.error('Failed to access media devices:', err);
      alert('Could not access microphone or camera. Please check permissions.');
      throw err;
    }
  };

  // Helper to initialize RTCPeerConnection
  const setupPeerConnection = (stream, partnerId) => {
    const pc = new RTCPeerConnection(rtcConfig);
    peerConnectionRef.current = pc;

    // Add local tracks to connection
    stream.getTracks().forEach((track) => {
      pc.addTrack(track, stream);
    });

    // Handle ICE candidates generated by browser
    pc.onicecandidate = (event) => {
      if (event.candidate && socket) {
        socket.emit('ice_candidate', {
          to: partnerId,
          candidate: event.candidate,
        });
      }
    };

    // Receive remote tracks
    pc.ontrack = (event) => {
      if (event.streams && event.streams[0]) {
        setRemoteStream(event.streams[0]);
      }
    };

    return pc;
  };

  // Initiate outgoing call
  const initiateCall = async (targetUser, type) => {
    setCallState('calling');
    setCallType(type);
    setPartner(targetUser);
    partnerIdRef.current = targetUser._id;

    try {
      const stream = await getMediaStream(type);
      const pc = setupPeerConnection(stream, targetUser._id);

      const offer = await pc.createOffer();
      await pc.setLocalDescription(offer);

      if (socket) {
        socket.emit('call_user', {
          userToCall: targetUser._id,
          signalData: offer,
          from: user._id,
          callerName: user.fullName,
          type: type,
        });
      }
    } catch (err) {
      console.error(err);
      cleanupCall();
    }
  };

  // Accept incoming call
  const acceptCall = async () => {
    if (!partnerIdRef.current || !incomingSignalRef.current) return;
    
    setCallState('connected');
    
    try {
      const stream = await getMediaStream(callType);
      const pc = setupPeerConnection(stream, partnerIdRef.current);

      await pc.setRemoteDescription(new RTCSessionDescription(incomingSignalRef.current));
      
      const answer = await pc.createAnswer();
      await pc.setLocalDescription(answer);

      if (socket) {
        socket.emit('answer_call', {
          to: partnerIdRef.current,
          signal: answer,
        });
      }

      // Process any ICE candidates received early
      while (pendingCandidates.current.length > 0) {
        const cand = pendingCandidates.current.shift();
        await pc.addIceCandidate(new RTCIceCandidate(cand));
      }
    } catch (err) {
      console.error(err);
      cleanupCall();
    }
  };

  // Reject incoming call
  const rejectCall = () => {
    if (socket && partnerIdRef.current) {
      socket.emit('reject_call', { to: partnerIdRef.current });
    }
    cleanupCall();
  };

  // Terminate active call
  const endCall = () => {
    if (socket && partnerIdRef.current) {
      socket.emit('hangup_call', { to: partnerIdRef.current });
    }
    // Save call log in database in background
    if (partnerIdRef.current) {
      api.post('/messages', {
        chatId: partnerIdRef.current, // Log via API helper
        ciphertext: 'Call Session ended',
        iv: '000000000000000000000000',
        messageType: 'text',
      }).catch(err => console.log('Error creating call log message'));
    }
    cleanupCall();
  };

  // Mute audio track
  const toggleMute = () => {
    if (localStreamRef.current) {
      const audioTrack = localStreamRef.current.getAudioTracks()[0];
      if (audioTrack) {
        audioTrack.enabled = !audioTrack.enabled;
        setIsMuted(!audioTrack.enabled);
      }
    }
  };

  // Toggle camera video track
  const toggleCamera = () => {
    if (localStreamRef.current && callType === 'video') {
      const videoTrack = localStreamRef.current.getVideoTracks()[0];
      if (videoTrack) {
        videoTrack.enabled = !videoTrack.enabled;
        setIsCameraOff(!videoTrack.enabled);
      }
    }
  };

  // Toggle browser tab/screen sharing
  const toggleScreenShare = async () => {
    if (isScreenSharing) {
      // Stop screen sharing and return to webcam
      if (screenStreamRef.current) {
        screenStreamRef.current.getTracks().forEach(t => t.stop());
      }
      
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: true });
        const newVideoTrack = stream.getVideoTracks()[0];
        
        // Swap video track on PC sender
        const pc = peerConnectionRef.current;
        if (pc) {
          const sender = pc.getSenders().find(s => s.track.kind === 'video');
          if (sender) {
            sender.replaceTrack(newVideoTrack);
          }
        }
        
        // Update local tracks state
        const oldVideoTrack = localStreamRef.current.getVideoTracks()[0];
        if (oldVideoTrack) oldVideoTrack.stop();
        
        localStreamRef.current.removeTrack(oldVideoTrack);
        localStreamRef.current.addTrack(newVideoTrack);
        
        setIsScreenSharing(false);
      } catch (err) {
        console.error('Error restoring camera stream:', err);
      }
    } else {
      // Start screen capture
      try {
        const stream = await navigator.mediaDevices.getDisplayMedia({ video: true });
        screenStreamRef.current = stream;
        const newVideoTrack = stream.getVideoTracks()[0];

        // Swap video track on PC sender
        const pc = peerConnectionRef.current;
        if (pc) {
          const sender = pc.getSenders().find(s => s.track.kind === 'video');
          if (sender) {
            sender.replaceTrack(newVideoTrack);
          }
        }

        // Listen for user clicking "Stop Sharing" overlay in browser
        newVideoTrack.onended = () => {
          toggleScreenShare(); // Revert back
        };

        // Update local tracks state
        const oldVideoTrack = localStreamRef.current.getVideoTracks()[0];
        if (oldVideoTrack) oldVideoTrack.stop();

        localStreamRef.current.removeTrack(oldVideoTrack);
        localStreamRef.current.addTrack(newVideoTrack);

        setIsScreenSharing(true);
      } catch (err) {
        console.error('Error starting screen share:', err);
      }
    }
  };

  const cleanupCall = () => {
    // Stop local stream tracks
    if (localStreamRef.current) {
      localStreamRef.current.getTracks().forEach((track) => track.stop());
    }
    // Stop screen capture tracks if any
    if (screenStreamRef.current) {
      screenStreamRef.current.getTracks().forEach((track) => track.stop());
    }

    // Close peer connection
    if (peerConnectionRef.current) {
      peerConnectionRef.current.close();
    }

    // Clear references and state
    peerConnectionRef.current = null;
    localStreamRef.current = null;
    screenStreamRef.current = null;
    pendingCandidates.current = [];
    partnerIdRef.current = null;
    incomingSignalRef.current = null;

    setCallState('idle');
    setPartner(null);
    setLocalStream(null);
    setRemoteStream(null);
    setIsMuted(false);
    setIsCameraOff(false);
    setIsScreenSharing(false);
  };

  return (
    <CallContext.Provider
      value={{
        callState,
        callType,
        partner,
        localStream,
        remoteStream,
        isMuted,
        isCameraOff,
        isScreenSharing,
        initiateCall,
        acceptCall,
        rejectCall,
        endCall,
        toggleMute,
        toggleCamera,
        toggleScreenShare,
      }}
    >
      {children}
    </CallContext.Provider>
  );
};
